# coding: utf-8

"""
    OpenRemote Manager REST API

    This is the documentation for the OpenRemote Manager HTTP REST API.  Please see the [documentation](https://docs.openremote.io) for more info.

    The version of the OpenAPI document: 3.0.0
    Contact: info@openremote.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501



import unittest

from or_rest_client.models.realm import Realm

class TestRealm(unittest.TestCase):
    """Realm unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Realm:
        """Test Realm
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Realm`
        """
        model = Realm()
        if include_optional:
            return Realm(
                id = '',
                name = '',
                display_name = '',
                enabled = True,
                not_before = 1.337,
                password_policy = [
                    ''
                    ],
                reset_password_allowed = True,
                duplicate_emails_allowed = True,
                remember_me = True,
                registration_allowed = True,
                registration_email_as_username = True,
                verify_email = True,
                login_with_email = True,
                login_theme = '',
                account_theme = '',
                admin_theme = '',
                email_theme = '',
                access_token_lifespan = 56,
                realm_roles = [
                    or_rest_client.models.realm_role.RealmRole(
                        name = '', 
                        description = '', )
                    ]
            )
        else:
            return Realm(
        )
        """

    def testRealm(self):
        """Test Realm"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
