# coding: utf-8

"""
    OpenRemote Manager REST API

    This is the documentation for the OpenRemote Manager HTTP REST API.  Please see the [documentation](https://docs.openremote.io) for more info.

    The version of the OpenAPI document: 3.0.0
    Contact: info@openremote.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501



import unittest

from or_rest_client.api.agent_api import AgentApi


class TestAgentApi(unittest.TestCase):
    """AgentApi unit test stubs"""

    def setUp(self) -> None:
        self.api = AgentApi()

    def tearDown(self) -> None:
        pass

    def test_do_protocol_asset_discovery(self) -> None:
        """Test case for do_protocol_asset_discovery

        Do protocol asset discovery
        """
        pass

    def test_do_protocol_asset_import(self) -> None:
        """Test case for do_protocol_asset_import

        Do protocol asset import
        """
        pass

    def test_do_protocol_instance_discovery(self) -> None:
        """Test case for do_protocol_instance_discovery

        Do protocol instance discovery
        """
        pass


if __name__ == '__main__':
    unittest.main()
