# coding: utf-8

"""
    OpenRemote Manager REST API

    This is the documentation for the OpenRemote Manager HTTP REST API.  Please see the [documentation](https://docs.openremote.io) for more info.

    The version of the OpenAPI document: 3.0.0
    Contact: info@openremote.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501



import unittest

from or_rest_client.models.name_value_predicate import NameValuePredicate

class TestNameValuePredicate(unittest.TestCase):
    """NameValuePredicate unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> NameValuePredicate:
        """Test NameValuePredicate
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `NameValuePredicate`
        """
        model = NameValuePredicate()
        if include_optional:
            return NameValuePredicate(
                name = or_rest_client.models.string_predicate.StringPredicate(
                    match = 'EXACT', 
                    case_sensitive = True, 
                    value = '', 
                    negate = True, ),
                negated = True,
                path = [
                    None
                    ],
                value = or_rest_client.models.value_predicate.ValuePredicate(
                    predicate_type = '', )
            )
        else:
            return NameValuePredicate(
        )
        """

    def testNameValuePredicate(self):
        """Test NameValuePredicate"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
