# coding: utf-8

"""
    OpenRemote Manager REST API

    This is the documentation for the OpenRemote Manager HTTP REST API.  Please see the [documentation](https://docs.openremote.io) for more info.

    The version of the OpenAPI document: 3.0.0
    Contact: info@openremote.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501



import unittest

from or_rest_client.api.services_api import ServicesApi


class TestServicesApi(unittest.TestCase):
    """ServicesApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ServicesApi()

    def tearDown(self) -> None:
        pass

    def test_deregister_service(self) -> None:
        """Test case for deregister_service

        Deregister an external service
        """
        pass

    def test_get_global_services(self) -> None:
        """Test case for get_global_services

        List all registered external services that are globally accessible within the OpenRemote manager
        """
        pass

    def test_get_service(self) -> None:
        """Test case for get_service

        Retrieve a specific external service by its serviceId and instanceId
        """
        pass

    def test_get_services(self) -> None:
        """Test case for get_services

        List all registered external services for the given realm within the OpenRemote manager
        """
        pass

    def test_heartbeat(self) -> None:
        """Test case for heartbeat

        Update the active registration lease for the specified external service
        """
        pass

    def test_register_global_service(self) -> None:
        """Test case for register_global_service

        Register a global external service with the OpenRemote manager
        """
        pass

    def test_register_service(self) -> None:
        """Test case for register_service

        Register an external service with the OpenRemote manager
        """
        pass


if __name__ == '__main__':
    unittest.main()
