# coding: utf-8

"""
    OpenRemote Manager REST API

    This is the documentation for the OpenRemote Manager HTTP REST API.  Please see the [documentation](https://docs.openremote.io) for more info.

    The version of the OpenAPI document: 3.0.0
    Contact: info@openremote.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501



import unittest

from or_rest_client.api.map_api import MapApi


class TestMapApi(unittest.TestCase):
    """MapApi unit test stubs"""

    def setUp(self) -> None:
        self.api = MapApi()

    def tearDown(self) -> None:
        pass

    def test_delete_map(self) -> None:
        """Test case for delete_map

        Removes mbtiles file
        """
        pass

    def test_get_custom_map_info(self) -> None:
        """Test case for get_custom_map_info

        Retrieve if the map is custom and custom map limit
        """
        pass

    def test_get_settings(self) -> None:
        """Test case for get_settings

        Retrieve the style used for Mapbox GL
        """
        pass

    def test_get_settings_js(self) -> None:
        """Test case for get_settings_js

        Retrieve the tileJSON object used for Mapbox GL
        """
        pass

    def test_get_tile(self) -> None:
        """Test case for get_tile

        Retrieve the vector tile data for Mapbox GL
        """
        pass

    def test_save_settings(self) -> None:
        """Test case for save_settings

        Update map settings
        """
        pass

    def test_upload_map(self) -> None:
        """Test case for upload_map

        Saves mbtiles file
        """
        pass


if __name__ == '__main__':
    unittest.main()
