# coding: utf-8

"""
    OpenRemote Manager REST API

    This is the documentation for the OpenRemote Manager HTTP REST API.  Please see the [documentation](https://docs.openremote.io) for more info.

    The version of the OpenAPI document: 3.0.0
    Contact: info@openremote.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501



import unittest

from or_rest_client.api.asset_datapoint_api import AssetDatapointApi


class TestAssetDatapointApi(unittest.TestCase):
    """AssetDatapointApi unit test stubs"""

    def setUp(self) -> None:
        self.api = AssetDatapointApi()

    def tearDown(self) -> None:
        pass

    def test_get_datapoint_export(self) -> None:
        """Test case for get_datapoint_export

        Retrieve a datapoint export of an asset attribute
        """
        pass

    def test_get_datapoint_period(self) -> None:
        """Test case for get_datapoint_period

        Retrieve a datapoint period of an asset attribute
        """
        pass

    def test_get_datapoints(self) -> None:
        """Test case for get_datapoints

        Retrieve the historical datapoints of an asset attribute
        """
        pass


if __name__ == '__main__':
    unittest.main()
