# coding: utf-8

"""
    OpenRemote Manager REST API

    This is the documentation for the OpenRemote Manager HTTP REST API.  Please see the [documentation](https://docs.openremote.io) for more info.

    The version of the OpenAPI document: 3.0.0
    Contact: info@openremote.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501



import unittest

from or_rest_client.models.map_source_config import MapSourceConfig

class TestMapSourceConfig(unittest.TestCase):
    """MapSourceConfig unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> MapSourceConfig:
        """Test MapSourceConfig
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `MapSourceConfig`
        """
        model = MapSourceConfig()
        if include_optional:
            return MapSourceConfig(
                type = '',
                url = '',
                tiles = [
                    ''
                    ],
                bounds = [
                    1.337
                    ],
                scheme = '',
                minzoom = 56,
                maxzoom = 56,
                attribution = '',
                custom = True
            )
        else:
            return MapSourceConfig(
        )
        """

    def testMapSourceConfig(self):
        """Test MapSourceConfig"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
