# coding: utf-8

"""
    OpenRemote Manager REST API

    This is the documentation for the OpenRemote Manager HTTP REST API.  Please see the [documentation](https://docs.openremote.io) for more info.

    The version of the OpenAPI document: 3.0.0
    Contact: info@openremote.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501



import unittest

from or_rest_client.models.boolean_predicate import BooleanPredicate

class TestBooleanPredicate(unittest.TestCase):
    """BooleanPredicate unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> BooleanPredicate:
        """Test BooleanPredicate
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `BooleanPredicate`
        """
        model = BooleanPredicate()
        if include_optional:
            return BooleanPredicate(
                value = True
            )
        else:
            return BooleanPredicate(
        )
        """

    def testBooleanPredicate(self):
        """Test BooleanPredicate"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
