# coding: utf-8

"""
    OpenRemote Manager REST API

    This is the documentation for the OpenRemote Manager HTTP REST API.  Please see the [documentation](https://docs.openremote.io) for more info.

    The version of the OpenAPI document: 3.0.0
    Contact: info@openremote.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501



import unittest

from or_rest_client.models.push_notification_message import PushNotificationMessage

class TestPushNotificationMessage(unittest.TestCase):
    """PushNotificationMessage unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PushNotificationMessage:
        """Test PushNotificationMessage
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PushNotificationMessage`
        """
        model = PushNotificationMessage()
        if include_optional:
            return PushNotificationMessage(
                title = '',
                body = '',
                action = or_rest_client.models.push_notification_action.PushNotificationAction(
                    url = '', 
                    data = or_rest_client.models.data.data(), 
                    silent = True, 
                    open_in_browser = True, 
                    http_method = '', ),
                buttons = [
                    or_rest_client.models.push_notification_button.PushNotificationButton(
                        title = '', 
                        action = or_rest_client.models.push_notification_action.PushNotificationAction(
                            url = '', 
                            data = or_rest_client.models.data.data(), 
                            silent = True, 
                            open_in_browser = True, 
                            http_method = '', ), )
                    ],
                data = {
                    'key' : None
                    },
                priority = 'NORMAL',
                target_type = 'DEVICE',
                target = '',
                expiration = 56
            )
        else:
            return PushNotificationMessage(
        )
        """

    def testPushNotificationMessage(self):
        """Test PushNotificationMessage"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
