# coding: utf-8

"""
    OpenRemote Manager REST API

    This is the documentation for the OpenRemote Manager HTTP REST API.  Please see the [documentation](https://docs.openremote.io) for more info.

    The version of the OpenAPI document: 3.0.0
    Contact: info@openremote.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501



import unittest

from or_rest_client.models.external_service import ExternalService

class TestExternalService(unittest.TestCase):
    """ExternalService unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ExternalService:
        """Test ExternalService
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ExternalService`
        """
        model = ExternalService()
        if include_optional:
            return ExternalService(
                realm = '',
                is_global = True,
                service_id = '012',
                instance_id = 56,
                version = '012',
                icon = '',
                label = '0',
                homepage_url = '012',
                status = 'AVAILABLE'
            )
        else:
            return ExternalService(
                service_id = '012',
                label = '0',
                homepage_url = '012',
                status = 'AVAILABLE',
        )
        """

    def testExternalService(self):
        """Test ExternalService"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
