# coding: utf-8

"""
    OpenRemote Manager REST API

    This is the documentation for the OpenRemote Manager HTTP REST API.  Please see the [documentation](https://docs.openremote.io) for more info.

    The version of the OpenAPI document: 3.0.0
    Contact: info@openremote.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501



import unittest

from or_rest_client.api.asset_predicted_datapoint_api import AssetPredictedDatapointApi


class TestAssetPredictedDatapointApi(unittest.TestCase):
    """AssetPredictedDatapointApi unit test stubs"""

    def setUp(self) -> None:
        self.api = AssetPredictedDatapointApi()

    def tearDown(self) -> None:
        pass

    def test_get_predicted_datapoints(self) -> None:
        """Test case for get_predicted_datapoints

        Retrieve the predicted datapoints of an asset attribute
        """
        pass

    def test_write_predicted_datapoints(self) -> None:
        """Test case for write_predicted_datapoints

        Write the predicted datapoints of an asset attribute
        """
        pass


if __name__ == '__main__':
    unittest.main()
