# coding: utf-8

"""
    OpenRemote Manager REST API

    This is the documentation for the OpenRemote Manager HTTP REST API.  Please see the [documentation](https://docs.openremote.io) for more info.

    The version of the OpenAPI document: 3.0.0
    Contact: info@openremote.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501



import unittest

from or_rest_client.models.x509_provisioning_data import X509ProvisioningData

class TestX509ProvisioningData(unittest.TestCase):
    """X509ProvisioningData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> X509ProvisioningData:
        """Test X509ProvisioningData
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `X509ProvisioningData`
        """
        model = X509ProvisioningData()
        if include_optional:
            return X509ProvisioningData(
                ca_cert_pem = '',
                ignore_expiry_date = True
            )
        else:
            return X509ProvisioningData(
        )
        """

    def testX509ProvisioningData(self):
        """Test X509ProvisioningData"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
