# coding: utf-8

"""
    OpenRemote Manager REST API

    This is the documentation for the OpenRemote Manager HTTP REST API.  Please see the [documentation](https://docs.openremote.io) for more info.

    The version of the OpenAPI document: 3.0.0
    Contact: info@openremote.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501



import unittest

from or_rest_client.api.realm_api import RealmApi


class TestRealmApi(unittest.TestCase):
    """RealmApi unit test stubs"""

    def setUp(self) -> None:
        self.api = RealmApi()

    def tearDown(self) -> None:
        pass

    def test_create_realm(self) -> None:
        """Test case for create_realm

        Create a new realm
        """
        pass

    def test_delete_realm(self) -> None:
        """Test case for delete_realm

        Delete a realm
        """
        pass

    def test_get_accessible_realms(self) -> None:
        """Test case for get_accessible_realms

        Retrieve accessible realms for the authenticated user
        """
        pass

    def test_get_all_realms(self) -> None:
        """Test case for get_all_realms

        Retrieve all realms
        """
        pass

    def test_get_realm(self) -> None:
        """Test case for get_realm

        Retrieve details about the currently authenticated and active realm
        """
        pass

    def test_update_realm(self) -> None:
        """Test case for update_realm

        Update a realm
        """
        pass


if __name__ == '__main__':
    unittest.main()
