# coding: utf-8

"""
    OpenRemote Manager REST API

    This is the documentation for the OpenRemote Manager HTTP REST API.  Please see the [documentation](https://docs.openremote.io) for more info.

    The version of the OpenAPI document: 3.0.0
    Contact: info@openremote.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501



import unittest

from or_rest_client.api.console_api import ConsoleApi


class TestConsoleApi(unittest.TestCase):
    """ConsoleApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ConsoleApi()

    def tearDown(self) -> None:
        pass

    def test_register(self) -> None:
        """Test case for register

        Create or update the registration for a console
        """
        pass


if __name__ == '__main__':
    unittest.main()
