# coding: utf-8

"""
    OpenRemote Manager REST API

    This is the documentation for the OpenRemote Manager HTTP REST API.  Please see the [documentation](https://docs.openremote.io) for more info.

    The version of the OpenAPI document: 3.0.0
    Contact: info@openremote.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501



import unittest

from or_rest_client.models.dashboard_grid_item import DashboardGridItem

class TestDashboardGridItem(unittest.TestCase):
    """DashboardGridItem unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DashboardGridItem:
        """Test DashboardGridItem
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DashboardGridItem`
        """
        model = DashboardGridItem()
        if include_optional:
            return DashboardGridItem(
                id = '',
                x = 56,
                y = 56,
                w = 1,
                h = 1,
                min_h = 56,
                min_w = 56,
                min_pixel_h = 56,
                min_pixel_w = 56,
                no_resize = True,
                no_move = True,
                locked = True
            )
        else:
            return DashboardGridItem(
        )
        """

    def testDashboardGridItem(self):
        """Test DashboardGridItem"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
