# coding: utf-8

"""
    OpenRemote Manager REST API

    This is the documentation for the OpenRemote Manager HTTP REST API.  Please see the [documentation](https://docs.openremote.io) for more info.

    The version of the OpenAPI document: 3.0.0
    Contact: info@openremote.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from importlib import import_module
from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing import Optional, Set
from typing_extensions import Self

from typing import TYPE_CHECKING
if TYPE_CHECKING:
    from openremote_openapi_client.models.asset_datapoint_all_query import AssetDatapointAllQuery
    from openremote_openapi_client.models.asset_datapoint_interval_query import AssetDatapointIntervalQuery
    from openremote_openapi_client.models.asset_datapoint_lttb_query import AssetDatapointLTTBQuery
    from openremote_openapi_client.models.asset_datapoint_nearest_query import AssetDatapointNearestQuery

class AssetDatapointQuery(BaseModel):
    """
    AssetDatapointQuery
    """ # noqa: E501
    from_timestamp: Optional[StrictInt] = Field(default=None, alias="fromTimestamp")
    to_timestamp: Optional[StrictInt] = Field(default=None, alias="toTimestamp")
    from_time: Optional[datetime] = Field(default=None, alias="fromTime")
    to_time: Optional[datetime] = Field(default=None, alias="toTime")
    type: StrictStr
    __properties: ClassVar[List[str]] = ["fromTimestamp", "toTimestamp", "fromTime", "toTime", "type"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    # JSON field name that stores the object type
    __discriminator_property_name: ClassVar[str] = 'type'

    # discriminator mappings
    __discriminator_value_class_map: ClassVar[Dict[str, str]] = {
        'AssetDatapointAllQuery': 'AssetDatapointAllQuery','AssetDatapointIntervalQuery': 'AssetDatapointIntervalQuery','AssetDatapointLTTBQuery': 'AssetDatapointLTTBQuery','AssetDatapointNearestQuery': 'AssetDatapointNearestQuery'
    }

    @classmethod
    def get_discriminator_value(cls, obj: Dict[str, Any]) -> Optional[str]:
        """Returns the discriminator value (object type) of the data"""
        discriminator_value = obj[cls.__discriminator_property_name]
        if discriminator_value:
            return cls.__discriminator_value_class_map.get(discriminator_value)
        else:
            return None

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Union[AssetDatapointAllQuery, AssetDatapointIntervalQuery, AssetDatapointLTTBQuery, AssetDatapointNearestQuery]]:
        """Create an instance of AssetDatapointQuery from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict[str, Any]) -> Optional[Union[AssetDatapointAllQuery, AssetDatapointIntervalQuery, AssetDatapointLTTBQuery, AssetDatapointNearestQuery]]:
        """Create an instance of AssetDatapointQuery from a dict"""
        # look up the object type based on discriminator mapping
        object_type = cls.get_discriminator_value(obj)
        if object_type ==  'AssetDatapointAllQuery':
            return import_module("openremote_openapi_client.models.asset_datapoint_all_query").AssetDatapointAllQuery.from_dict(obj)
        if object_type ==  'AssetDatapointIntervalQuery':
            return import_module("openremote_openapi_client.models.asset_datapoint_interval_query").AssetDatapointIntervalQuery.from_dict(obj)
        if object_type ==  'AssetDatapointLTTBQuery':
            return import_module("openremote_openapi_client.models.asset_datapoint_lttb_query").AssetDatapointLTTBQuery.from_dict(obj)
        if object_type ==  'AssetDatapointNearestQuery':
            return import_module("openremote_openapi_client.models.asset_datapoint_nearest_query").AssetDatapointNearestQuery.from_dict(obj)

        raise ValueError("AssetDatapointQuery failed to lookup discriminator value from " +
                            json.dumps(obj) + ". Discriminator property name: " + cls.__discriminator_property_name +
                            ", mapping: " + json.dumps(cls.__discriminator_value_class_map))


