# coding: utf-8

"""
    OpenRemote Manager REST API

    This is the documentation for the OpenRemote Manager HTTP REST API.  Please see the [documentation](https://docs.openremote.io) for more info.

    The version of the OpenAPI document: 3.0.0
    Contact: info@openremote.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from typing import Optional, Set
from typing_extensions import Self

class DashboardScreenPreset(BaseModel):
    """
    DashboardScreenPreset
    """ # noqa: E501
    id: Optional[StrictStr] = None
    display_name: Annotated[str, Field(min_length=1, strict=True)] = Field(alias="displayName")
    breakpoint: Optional[Annotated[int, Field(strict=True, ge=1)]] = None
    scaling_preset: StrictStr = Field(alias="scalingPreset")
    redirect_dashboard_id: Optional[StrictStr] = Field(default=None, alias="redirectDashboardId")
    __properties: ClassVar[List[str]] = ["id", "displayName", "breakpoint", "scalingPreset", "redirectDashboardId"]

    @field_validator('scaling_preset')
    def scaling_preset_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['WRAP_TO_SINGLE_COLUMN', 'KEEP_LAYOUT', 'REDIRECT', 'BLOCK_DEVICE']):
            raise ValueError("must be one of enum values ('WRAP_TO_SINGLE_COLUMN', 'KEEP_LAYOUT', 'REDIRECT', 'BLOCK_DEVICE')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of DashboardScreenPreset from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of DashboardScreenPreset from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "displayName": obj.get("displayName"),
            "breakpoint": obj.get("breakpoint"),
            "scalingPreset": obj.get("scalingPreset"),
            "redirectDashboardId": obj.get("redirectDashboardId")
        })
        return _obj


