# coding: utf-8

"""
    OpenRemote Manager REST API

    This is the documentation for the OpenRemote Manager HTTP REST API.  Please see the [documentation](https://docs.openremote.io) for more info.

    The version of the OpenAPI document: 3.0.0
    Contact: info@openremote.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from typing import Optional, Set
from typing_extensions import Self

class ExternalService(BaseModel):
    """
    ExternalService
    """ # noqa: E501
    realm: Optional[StrictStr] = None
    is_global: Optional[StrictBool] = Field(default=None, alias="isGlobal")
    service_id: Annotated[str, Field(min_length=3, strict=True, max_length=255)] = Field(alias="serviceId")
    instance_id: Optional[StrictInt] = Field(default=None, alias="instanceId")
    version: Optional[Annotated[str, Field(min_length=3, strict=True, max_length=255)]] = None
    icon: Optional[StrictStr] = None
    label: Annotated[str, Field(min_length=1, strict=True, max_length=255)]
    homepage_url: Annotated[str, Field(min_length=3, strict=True, max_length=512)] = Field(alias="homepageUrl")
    status: StrictStr
    __properties: ClassVar[List[str]] = ["realm", "isGlobal", "serviceId", "instanceId", "version", "icon", "label", "homepageUrl", "status"]

    @field_validator('status')
    def status_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['AVAILABLE', 'UNAVAILABLE']):
            raise ValueError("must be one of enum values ('AVAILABLE', 'UNAVAILABLE')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ExternalService from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        """
        excluded_fields: Set[str] = set([
            "realm",
            "is_global",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ExternalService from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "realm": obj.get("realm"),
            "isGlobal": obj.get("isGlobal"),
            "serviceId": obj.get("serviceId"),
            "instanceId": obj.get("instanceId"),
            "version": obj.get("version"),
            "icon": obj.get("icon"),
            "label": obj.get("label"),
            "homepageUrl": obj.get("homepageUrl"),
            "status": obj.get("status")
        })
        return _obj


