# coding: utf-8

"""
    OpenRemote Manager REST API

    This is the documentation for the OpenRemote Manager HTTP REST API.  Please see the [documentation](https://docs.openremote.io) for more info.

    The version of the OpenAPI document: 3.0.0
    Contact: info@openremote.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from importlib import import_module
from pydantic import BaseModel, ConfigDict, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing import Optional, Set
from typing_extensions import Self

from typing import TYPE_CHECKING
if TYPE_CHECKING:
    from or_rest_client.models.allowed_values import AllowedValues
    from or_rest_client.models.future import Future
    from or_rest_client.models.future_or_present import FutureOrPresent
    from or_rest_client.models.max import Max
    from or_rest_client.models.min import Min
    from or_rest_client.models.not_blank import NotBlank
    from or_rest_client.models.not_empty import NotEmpty
    from or_rest_client.models.not_null import NotNull
    from or_rest_client.models.past import Past
    from or_rest_client.models.past_or_present import PastOrPresent
    from or_rest_client.models.pattern import Pattern
    from or_rest_client.models.size import Size

class ValueConstraint(BaseModel):
    """
    ValueConstraint
    """ # noqa: E501
    message: Optional[StrictStr] = None
    type: StrictStr
    __properties: ClassVar[List[str]] = ["message", "type"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    # JSON field name that stores the object type
    __discriminator_property_name: ClassVar[str] = 'type'

    # discriminator mappings
    __discriminator_value_class_map: ClassVar[Dict[str, str]] = {
        'AllowedValues': 'AllowedValues','Future': 'Future','FutureOrPresent': 'FutureOrPresent','Max': 'Max','Min': 'Min','NotBlank': 'NotBlank','NotEmpty': 'NotEmpty','NotNull': 'NotNull','Past': 'Past','PastOrPresent': 'PastOrPresent','Pattern': 'Pattern','Size': 'Size'
    }

    @classmethod
    def get_discriminator_value(cls, obj: Dict[str, Any]) -> Optional[str]:
        """Returns the discriminator value (object type) of the data"""
        discriminator_value = obj[cls.__discriminator_property_name]
        if discriminator_value:
            return cls.__discriminator_value_class_map.get(discriminator_value)
        else:
            return None

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Union[AllowedValues, Future, FutureOrPresent, Max, Min, NotBlank, NotEmpty, NotNull, Past, PastOrPresent, Pattern, Size]]:
        """Create an instance of ValueConstraint from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict[str, Any]) -> Optional[Union[AllowedValues, Future, FutureOrPresent, Max, Min, NotBlank, NotEmpty, NotNull, Past, PastOrPresent, Pattern, Size]]:
        """Create an instance of ValueConstraint from a dict"""
        # look up the object type based on discriminator mapping
        object_type = cls.get_discriminator_value(obj)
        if object_type ==  'AllowedValues':
            return import_module("or_rest_client.models.allowed_values").AllowedValues.from_dict(obj)
        if object_type ==  'Future':
            return import_module("or_rest_client.models.future").Future.from_dict(obj)
        if object_type ==  'FutureOrPresent':
            return import_module("or_rest_client.models.future_or_present").FutureOrPresent.from_dict(obj)
        if object_type ==  'Max':
            return import_module("or_rest_client.models.max").Max.from_dict(obj)
        if object_type ==  'Min':
            return import_module("or_rest_client.models.min").Min.from_dict(obj)
        if object_type ==  'NotBlank':
            return import_module("or_rest_client.models.not_blank").NotBlank.from_dict(obj)
        if object_type ==  'NotEmpty':
            return import_module("or_rest_client.models.not_empty").NotEmpty.from_dict(obj)
        if object_type ==  'NotNull':
            return import_module("or_rest_client.models.not_null").NotNull.from_dict(obj)
        if object_type ==  'Past':
            return import_module("or_rest_client.models.past").Past.from_dict(obj)
        if object_type ==  'PastOrPresent':
            return import_module("or_rest_client.models.past_or_present").PastOrPresent.from_dict(obj)
        if object_type ==  'Pattern':
            return import_module("or_rest_client.models.pattern").Pattern.from_dict(obj)
        if object_type ==  'Size':
            return import_module("or_rest_client.models.size").Size.from_dict(obj)

        raise ValueError("ValueConstraint failed to lookup discriminator value from " +
                            json.dumps(obj) + ". Discriminator property name: " + cls.__discriminator_property_name +
                            ", mapping: " + json.dumps(cls.__discriminator_value_class_map))


